package examples.unit01.components.table.withdb.ui;

import java.util.Date;
import java.awt.Frame;

import examples.unit01.components.table.withdb.dtos.Cliente;
import examples.unit01.components.table.withdb.services.ClientesService;
import examples.unit01.components.table.withdb.services.IClientesService;

public class ClienteDialog extends javax.swing.JDialog {

    private IClientesService service = ClientesService.getInstance();


    
    public ClienteDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(300, 200);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblFechaAlta = new javax.swing.JLabel();
        spnFechaAlta = new javax.swing.JSpinner();
        lblProvincia = new javax.swing.JLabel();
        cmbProvincia = new javax.swing.JComboBox<>();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 2));

        lblNombre.setText("Nombre: ");
        getContentPane().add(lblNombre);
        getContentPane().add(txtNombre);

        lblApellidos.setText("Apellido: ");
        getContentPane().add(lblApellidos);
        getContentPane().add(txtApellidos);

        lblFechaAlta.setText("Fecha Alta");
        getContentPane().add(lblFechaAlta);

        spnFechaAlta.setModel(new javax.swing.SpinnerDateModel(new Date(), new Date(946681200000L), null, java.util.Calendar.DAY_OF_MONTH));
        getContentPane().add(spnFechaAlta);

        lblProvincia.setText("Provincia");
        getContentPane().add(lblProvincia);

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asturias", "Cantabria", "Galicia", "Pais Vasco" }));
        getContentPane().add(cmbProvincia);

        btnOk.setText("Aceptar");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        
        Cliente cliente = new Cliente(
                txtNombre.getText(),
                txtApellidos.getText(),
                (Date)spnFechaAlta.getValue(),
                (String)cmbProvincia.getSelectedItem()
        );
        
        service.add(cliente);
        dispose();
                
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblFechaAlta;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JSpinner spnFechaAlta;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
