package examples.unit01.components.table.withdb.ui;

import java.util.stream.IntStream;
import javax.swing.table.DefaultTableModel;

import examples.unit01.components.table.withdb.services.ClientesService;
import examples.unit01.components.table.withdb.services.IClientesService;
import examples.unit01.components.table.withdb.ui.ClienteDialog;
import examples.unit01.components.table.withdb.ui.models.ClientesModel;


/**
 *
 * @author German
 */
public final class MainFrame extends javax.swing.JFrame {

    private IClientesService service = ClientesService.getInstance();
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        refreshModel();
    }
    
    /*
    public void refreshModel() {
        DefaultTableModel model = new CustomModel();
        
        for (Cliente c: service.getAll())
            model.addRow(c.getValues());
        tblClientes.setModel(model);
    }
    */
    
    public void refreshModel() {
        ClientesModel model = new ClientesModel(service.getAll());
        tblClientes.setModel(model);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTable = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        mnuBar = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mnuAltaCliente = new javax.swing.JMenuItem();
        mnuDeleteSelected = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Clientes");

        tblClientes.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Apellidos", "Nombre", "Alta", "Provincia"
            }
        ) {
            Class[] types = new Class [] {
                String.class, String.class, Object.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblClientes.setName("tblClientes"); // NOI18N
        scrollTable.setViewportView(tblClientes);

        getContentPane().add(scrollTable, java.awt.BorderLayout.CENTER);

        mnuBar.setName("mnuBar"); // NOI18N

        mnuClientes.setText("Clientes");
        mnuClientes.setName("mnuClients"); // NOI18N

        mnuAltaCliente.setText("Alta");
        mnuAltaCliente.setName("mnuNewClient"); // NOI18N
        mnuAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuAltaCliente);

        mnuDeleteSelected.setText("Borrar Seleccionados");
        mnuDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteSelectedActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuDeleteSelected);

        mnuBar.add(mnuClientes);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaClienteActionPerformed
        ClienteDialog clienteDialog = new ClienteDialog(this, true);
        clienteDialog.setResizable(false);
        clienteDialog.setVisible(true);
        refreshModel();
    }//GEN-LAST:event_mnuAltaClienteActionPerformed

    private void mnuDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteSelectedActionPerformed
        /*
        IntStream.of(tblClientes.getSelectedRows())
                .boxed()
                .sorted(Collections.reverseOrder())
                .map(tblClientes::convertRowIndexToModel)
                .forEach(service::delete);
        */
        
        int[] keys = IntStream.of(tblClientes.getSelectedRows())
            .map(i -> (int)tblClientes.getValueAt(i,0))
            .toArray();
        
        IntStream.of(keys).forEach(service::delete);
        /*
        IntStream.of(tblClientes.getSelectedRows())

                .map(i -> tblClientes.convertRowIndexToModel(i))
                .forEach(i -> service.delete(i));
        */
        refreshModel();

        
 
    }//GEN-LAST:event_mnuDeleteSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuAltaCliente;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuDeleteSelected;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
