
package examples.unit01.components.table.customtable.ui;

import examples.unit01.components.table.customtable.services.ClientesService;
import examples.unit01.components.table.customtable.services.IClientesService;
import examples.unit01.components.table.customtable.ui.models.CustomModel;

import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author German
 */
public final class MainFrame extends javax.swing.JFrame {
    
    private IClientesService service;
    private CustomModel model;
    TableRowSorter<CustomModel> sorter;

    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        service = ClientesService.getInstance();
        refreshModel();

    }
    
    public void refreshModel() {
        model = new CustomModel(service.getAll());
        tblAlumnos.setModel(model);
       
        sorter = new TableRowSorter<>(model);
        tblAlumnos.setRowSorter(sorter);
       
        List<RowSorter.SortKey> keys = new ArrayList<>();   
        keys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(keys);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTable = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        pnlButtons = new javax.swing.JPanel();
        btnShow = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        btnFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Clientes");

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAlumnos.setName("tblAlumnos"); // NOI18N
        scrollTable.setViewportView(tblAlumnos);

        getContentPane().add(scrollTable, java.awt.BorderLayout.CENTER);

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        pnlButtons.add(btnShow);
        pnlButtons.add(lblResult);

        txtFilter.setColumns(15);
        pnlButtons.add(txtFilter);

        btnFilter.setText("Filter");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        pnlButtons.add(btnFilter);

        getContentPane().add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        int selected = tblAlumnos.convertRowIndexToModel(
                tblAlumnos.getSelectedRow()
        );
        lblResult.setText(service.getAll().get(selected).getNombre());
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        RowFilter<CustomModel, Integer> rf = RowFilter.regexFilter(txtFilter.getText(), 0);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_btnFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
