
package examples.unit01.components.table.customtable.ui;

import com.german.ui.models.CustomModel;
import examples.unit01.components.table.customtable.services.ClientesService;
import examples.unit01.components.table.customtable.services.IClientesService;
import examples.unit01.components.table.customtable.ui.models.ClientesModel;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author German
 */
public final class MainFrame extends javax.swing.JFrame {

    private final IClientesService service = ClientesService.getInstance();
    private ClientesModel model;
    private TableRowSorter<ClientesModel> sorter;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        refreshModel();
    }
    
    public void refreshModel() {
        model = new ClientesModel(service.getAll());
        tblClientes.setModel(model);
        
        sorter = new TableRowSorter<>(model);
        tblClientes.setRowSorter(sorter);
        
        List<RowSorter.SortKey> keys = new ArrayList<>();   
        keys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(keys);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTable = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnFilter = new javax.swing.JButton();
        txtFilter = new javax.swing.JTextField();
        mnuBar = new javax.swing.JMenuBar();
        mnuClientes = new javax.swing.JMenu();
        mnuAltaCliente = new javax.swing.JMenuItem();
        mnuDeleteSelected = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario Clientes");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Apellidos", "Nombre", "Alta", "Provincia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblClientes.setName("tblClientes"); // NOI18N
        scrollTable.setViewportView(tblClientes);

        getContentPane().add(scrollTable, java.awt.BorderLayout.CENTER);

        btnFilter.setText("Filtrar");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jPanel1.add(btnFilter);

        txtFilter.setColumns(20);
        jPanel1.add(txtFilter);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        mnuBar.setName("mnuBar"); // NOI18N

        mnuClientes.setText("Clientes");
        mnuClientes.setName("mnuClients"); // NOI18N

        mnuAltaCliente.setText("Alta");
        mnuAltaCliente.setName("mnuNewClient"); // NOI18N
        mnuAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAltaClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuAltaCliente);

        mnuDeleteSelected.setText("Borrar Seleccionados");
        mnuDeleteSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteSelectedActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuDeleteSelected);

        mnuBar.add(mnuClientes);

        setJMenuBar(mnuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaClienteActionPerformed
        ClienteDialog clienteDialog = new ClienteDialog(this, true);
        clienteDialog.setResizable(false);
        clienteDialog.setVisible(true);
        refreshModel();
    }//GEN-LAST:event_mnuAltaClienteActionPerformed

    private void mnuDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteSelectedActionPerformed

        // Obtengo los ids de cada cliente
        int[] keys = IntStream.of(tblClientes.getSelectedRows())
            .map(i -> (int)tblClientes.getValueAt(i,0))
            .toArray();
        
        // Borro cada uno de los keys
        IntStream.of(keys).forEach(service::delete);

        // Refresh the model
        refreshModel();
    }//GEN-LAST:event_mnuDeleteSelectedActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        RowFilter<ClientesModel, Integer> rf = RowFilter.regexFilter(txtFilter.getText());
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_btnFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnuAltaCliente;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuDeleteSelected;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
