package examples.unit01.components.listboxes.team.ui;


import examples.unit01.components.listboxes.team.model.Person;
import examples.unit01.components.listboxes.team.repositories.PersonRepository;
import examples.unit01.components.listboxes.team.services.IPersonService;
import examples.unit01.components.listboxes.team.services.PersonService;

import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {
    
    private int count = 4;
    private IPersonService service;
    private PeopleListModel peopleModel;
    private TeamListModel teamModel;
    public Main(IPersonService personService) {
        service = personService;
        peopleModel = new PeopleListModel(service.getAll());
        teamModel = new TeamListModel(service.getTeam());
        initComponents();
    }
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtSecondName = new javax.swing.JTextField();
        spnAge = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jspPeople = new javax.swing.JScrollPane();
        lstPeople = new javax.swing.JList<>();
        pnlInformation = new javax.swing.JPanel();
        lblInformation = new javax.swing.JLabel();
        lblInformationBlank = new javax.swing.JLabel();
        lblInformationFirstName = new javax.swing.JLabel();
        lblInformationFirstNameValue = new javax.swing.JLabel();
        lblInformationSecondName = new javax.swing.JLabel();
        lblInformationSecondNameValue = new javax.swing.JLabel();
        lblInformationAge = new javax.swing.JLabel();
        lblInformationAgeValue = new javax.swing.JLabel();
        btnRigth = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        pnlTeam = new javax.swing.JScrollPane();
        lstTeam = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblTitle.setText("Agregar Persona:");
        lblTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lblTitle, gridBagConstraints);

        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        getContentPane().add(lblNombre, gridBagConstraints);

        lblApellidos.setText("Apellidos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lblApellidos, gridBagConstraints);

        lblEdad.setText("Edad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lblEdad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        getContentPane().add(txtFirstName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(txtSecondName, gridBagConstraints);

        spnAge.setModel(new javax.swing.SpinnerNumberModel(18, 18, 100, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(spnAge, gridBagConstraints);

        btnAdd.setText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        getContentPane().add(btnAdd, gridBagConstraints);

        btnDel.setText("Borrar");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(btnDel, gridBagConstraints);

        jspPeople.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));

        lstPeople.setModel(peopleModel);
        lstPeople.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPeopleValueChanged(evt);
            }
        });
        jspPeople.setViewportView(lstPeople);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jspPeople, gridBagConstraints);

        pnlInformation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        pnlInformation.setLayout(new java.awt.GridLayout(4, 2, 2, 2));

        lblInformation.setText("Information:");
        pnlInformation.add(lblInformation);
        pnlInformation.add(lblInformationBlank);

        lblInformationFirstName.setText("Nombre:");
        pnlInformation.add(lblInformationFirstName);

        lblInformationFirstNameValue.setText("---");
        pnlInformation.add(lblInformationFirstNameValue);

        lblInformationSecondName.setText("Apellidos:");
        pnlInformation.add(lblInformationSecondName);

        lblInformationSecondNameValue.setText("---");
        pnlInformation.add(lblInformationSecondNameValue);

        lblInformationAge.setText("Edad:");
        pnlInformation.add(lblInformationAge);

        lblInformationAgeValue.setText("---");
        pnlInformation.add(lblInformationAgeValue);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(pnlInformation, gridBagConstraints);

        btnRigth.setText(">>>");
        btnRigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRigthActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        getContentPane().add(btnRigth, gridBagConstraints);

        btnLeft.setText("<<<");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        getContentPane().add(btnLeft, gridBagConstraints);

        pnlTeam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));

        lstTeam.setBorder(null);
        lstTeam.setModel(teamModel);
        pnlTeam.setViewportView(lstTeam);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 4.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(pnlTeam, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPeopleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPeopleValueChanged
        int index = lstPeople.getSelectedIndex();
        
        if (index != -1) {
            Person person = service.getAll().get(index);

            lblInformationFirstNameValue.setText(person.getFirstName());
            lblInformationSecondNameValue.setText(person.getSecondName());
            lblInformationAgeValue.setText(String.valueOf(person.getAge()));

            txtFirstName.setText(person.getFirstName());
            txtSecondName.setText(person.getSecondName());
            spnAge.setValue(person.getAge());
        }
    }//GEN-LAST:event_lstPeopleValueChanged

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        var index = lstPeople.getSelectedIndex();
        if (index != -1) {
            Person person = service.getAll().get(index);
            service.delete(person);
            peopleModel.fireIntervalRemoved(index);
        } else {
            JOptionPane.showMessageDialog(
                    this, 
                    "Debe seleccionar un elemento de la lista", 
                    "Mensaje", 
                    JOptionPane.WARNING_MESSAGE );
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Person person = new Person(
                count++,
                txtFirstName.getText(),
                txtSecondName.getText(),
                (int)spnAge.getValue()
        );
        service.add(person);
        peopleModel.fireIntervalAdded();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRigthActionPerformed
        int index = lstPeople.getSelectedIndex();
        if (index != -1) {
            Person person = service.getAll().get(index);
            service.changePersonToTeam(person);
            peopleModel.fireIntervalRemoved(index);
            teamModel.fireIntervalAdded();
        }else {
            JOptionPane.showMessageDialog(
                    this, 
                    "Debe seleccionar un elemento de la lista", 
                    "Mensaje", 
                    JOptionPane.WARNING_MESSAGE );
        }

    }//GEN-LAST:event_btnRigthActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        int index = lstTeam.getSelectedIndex();
        if (index != -1) {
            Person person = service.getTeam().get(index);
            service.changePersonToStack(person);
            peopleModel.fireIntervalAdded();
            teamModel.fireIntervalRemoved(index);
        }else {
            JOptionPane.showMessageDialog(
                    this, 
                    "Debe seleccionar un elemento de la lista", 
                    "Mensaje", 
                    JOptionPane.WARNING_MESSAGE );
        }
    }//GEN-LAST:event_btnLeftActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
            IPersonService service = new PersonService(new PersonRepository());
            new Main(service).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRigth;
    private javax.swing.JScrollPane jspPeople;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblInformation;
    private javax.swing.JLabel lblInformationAge;
    private javax.swing.JLabel lblInformationAgeValue;
    private javax.swing.JLabel lblInformationBlank;
    private javax.swing.JLabel lblInformationFirstName;
    private javax.swing.JLabel lblInformationFirstNameValue;
    private javax.swing.JLabel lblInformationSecondName;
    private javax.swing.JLabel lblInformationSecondNameValue;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstPeople;
    private javax.swing.JList<String> lstTeam;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JScrollPane pnlTeam;
    private javax.swing.JSpinner spnAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtSecondName;
    // End of variables declaration//GEN-END:variables
}
